import 'package:get/get.dart';

import '../utils/device_constants/appStrings.dart';

class AppLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    /// ---------- English ----------
    "en_US": {
      "app_title": "Tokrigo Wallet",
      "bonus_points": "Bonus Points",
      "direct_referrals": "Direct Referrals",
      "network_growing": "Your network is growing!",
      "manage_bills": "Manage Bills, Expenses & Future with Tokrigo Wallet Systems.",
      "direct_connection_list": "Direct Connection List",
      "no_direct_connections": "No direct connections yet.",
      "ok": "OK",
      "share_referral":
      "Share this referral code with friends and enjoy discounts on your next purchase!",
      "logout": "Logout",
      "referral": "My Referral",
      "message": "What is your name?",
      "name": "Tarun Jain",
      "current_balance": "Current Balance",
      "about_tokrigo_wallet": "About Tokrigo Wallet.",
      "tokrigo_wallet_description" : AppStrings.walletDescription_EN,
      "property" : "Property",
      "jobs" : "Jobs",
      "electricity_repair" : "Electric Repair",
      "insurance" : "Insurance",
      "finance_services" : "Finance Services",
      "legal_services" : "Legal Services",
      "tokrigo_Wallet_Module" : "Tokrigo Wallet Module",
      "login_screen" : "Login Screen",
      "signup_screen" : "Signup Screen",
      "login_button" : "Login",
      "signup_button" : "Sign up",
      "user_name" : "User Name",
      "please_enter_user_name" : "Please enter user name",
      "please_enter_email" : "Please enter email",
      "enter_valid_email" : "Enter valid email",
      "email" : "Email",
      "password" : "Password",
      "confirm_password" : "Confirm Password",
      "enter_email" : "Enter Email",
      "enter_password" : "Enter Password",
      "confirm_your_password" : "Confirm your password",
      "passwords_do_not_match" : "Passwords do not match",
      "referral_Code_optional" : "Referral Code (optional)",
      "dont_have_an_account?" : "Don't have an account?",
      "already_have_an_account?" : "Already have an account?",
    },

    /// ---------- Hindi ----------
    "hi_IN": {
      "app_title": "टोकरीगो वॉलेट",
      "bonus_points": "बोनस अंक",
      "direct_referrals": "प्रत्यक्ष रेफ़रल",
      "network_growing": "आपका नेटवर्क बढ़ रहा है!",
      "manage_bills":
      "टोकरीगो वॉलेट सिस्टम के साथ बिल, खर्च और भविष्य का प्रबंधन करें।",
      "direct_connection_list": "प्रत्यक्ष कनेक्शन सूची",
      "no_direct_connections": "अभी तक कोई प्रत्यक्ष कनेक्शन नहीं है।",
      "ok": "ठीक है",
      "share_referral":
      "अपने दोस्तों के साथ यह रेफ़रल कोड साझा करें और अगली खरीद पर छूट पाएं!",
      "logout": "लॉग आउट",
      "referral": "मेरा रेफ़रल",
      "message": "आपका क्या नाम है?",
      "name": "तरुण जैन",
      "current_balance": "वर्तमान शेष",
      "about_tokrigo_wallet": "टोक्रिगो वॉलेट के बारे में.",
      "tokrigo_wallet_description" : AppStrings.walletDescription_HIN,
      "property" : "भू संपत्ति",
      "jobs" : "नौकरियाँ",
      "electricity_repair" : "बिजली उपकरण मरम्मत",
      "insurance" : "बीमा",
      "finance_services" : "वित्त सेवाएँ",
      "legal_services" : "कानूनी सेवाओं",
      "tokrigo_Wallet_Module" :"टोक्रिगो वॉलेट मॉड्यूल",
      "login_screen" : "लॉगिन स्क्रीन",
      "signup_screen" : "साइनअप स्क्रीन",
      "login_button" : "लॉग इन करें",
      "signup_button" : "साइन अप करें",
      "user_name" : "उपयोगकर्ता का नाम",
      "please_enter_user_name" : "कृपया उपयोगकर्ता का नाम दर्ज करें",
      "please_enter_email" : "कृपया ईमेल दर्ज करें",
      "enter_valid_email" : "वैध ईमेल दर्ज करें",
      "email" : "ईमेल",
      "enter_email" : "ईमेल दर्ज करें",
      "enter_password" : "पासवर्ड दर्ज करें",
      "password" : "पासवर्ड",
      "confirm_password" : "पासवर्ड की पुष्टि कीजिये",
      "confirm_your_password" : "अपने पासवर्ड की पुष्टि करें",
      "passwords_do_not_match" : "सांकेतिक शब्द मेल नहीं खाते",
      "referral_Code_optional" : "रेफरल कोड (वैकल्पिक)",
      "dont_have_an_account?" : "क्या आपके पास खाता नहीं है?",
      "already_have_an_account?" : "क्या आपके पास पहले से एक खाता मौजूद है?",
    },
  };
}
